# Generated by Django 4.2.7 on 2025-08-28 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("loans", "0002_add_loan_type_default"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hrreview",
            name="is_approved",
        ),
        migrations.AddField(
            model_name="hrreview",
            name="additional_comments",
            field=models.TextField(
                blank=True, help_text="Additional HR comments and recommendations"
            ),
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="committee_approval_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="disbursement_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="final_approved_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="guarantor_approval_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="hr_review_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="loan_officer_approval_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="payment_processing_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="loanapplication",
            name="savings_value",
            field=models.DecimalField(
                decimal_places=2, help_text="Value of savings in TZS", max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="loanapplication",
            name="shares_value",
            field=models.DecimalField(
                decimal_places=2, help_text="Value of shares", max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="loanapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("guarantor_approved", "Guarantor Approved"),
                    ("hr_reviewed", "HR Reviewed"),
                    ("loan_officer_approved", "Loan Officer Approved"),
                    ("committee_approved", "Committee Approved"),
                    ("payment_processing", "Payment Processing"),
                    ("disbursed", "Disbursed"),
                    ("rejected", "Rejected"),
                    ("completed", "Completed"),
                ],
                default="pending",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="AccountantReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(default="Bank Transfer", max_length=50),
                ),
                (
                    "bank_details",
                    models.TextField(blank=True, help_text="Bank transfer details"),
                ),
                (
                    "processing_notes",
                    models.TextField(
                        blank=True, help_text="Processing notes and comments"
                    ),
                ),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "accountant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accountant_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "loan_application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accountant_reviews",
                        to="loans.loanapplication",
                    ),
                ),
            ],
        ),
    ]
