# Generated by Django 4.2.7 on 2025-08-30 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("loans", "0003_remove_hrreview_is_approved_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountantreview",
            name="accountant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accountant_reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="committeereview",
            name="committee_member",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="committee_reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="committeereview",
            name="is_approved",
            field=models.BooleanField(
                blank=True,
                help_text="True=Approved, False=Rejected, Null=Pending",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="hrreview",
            name="reviewer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hr_reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="loanofficerreview",
            name="is_approved",
            field=models.BooleanField(
                blank=True,
                help_text="True=Approved, False=Rejected, Null=Pending",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="loanofficerreview",
            name="officer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loan_officer_reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
